homeassistant:
  customize_glob:
    "sensor.hp_ink_level_*":
      icon: mdi:cup-water

      hidden: False
      homebridge_hidden: True

sensor:
  - platform: command_line
    name: HP Ink Level Black
    command: /usr/bin/snmpwalk -v1 -c public 192.168.86.21 1.3.6.1.2.1.43.11.1.1 | awk '/.*\.8\.0\.1/ { sub(/.*\./,""); split($0,TT,/[ "]*/); maxlevel=TT[4]; } /.*\.9\.0\.1/ { sub(/.*\./,""); split($0,TT,/[ "]*/); print TT[4] / maxlevel * 100; }'
    unit_of_measurement: '%'
    scan_interval: 14400

  - platform: command_line
    name: HP Ink Level Yellow
    command: /usr/bin/snmpwalk -v1 -c public 192.168.86.21 1.3.6.1.2.1.43.11.1.1 | awk '/.*\.8\.0\.2/ { sub(/.*\./,""); split($0,TT,/[ "]*/); maxlevel=TT[4]; } /.*\.9\.0\.2/ { sub(/.*\./,""); split($0,TT,/[ "]*/); print TT[4] / maxlevel * 100; }'
    unit_of_measurement: '%'
    scan_interval: 14400

  - platform: command_line
    name: HP Ink Level Cyan 
    command: /usr/bin/snmpwalk -v1 -c public 192.168.86.21 1.3.6.1.2.1.43.11.1.1 | awk '/.*\.8\.0\.3/ { sub(/.*\./,""); split($0,TT,/[ "]*/); maxlevel=TT[4]; } /.*\.9\.0\.3/ { sub(/.*\./,""); split($0,TT,/[ "]*/); print TT[4] / maxlevel * 100; }'
    unit_of_measurement: '%'
    scan_interval: 14400

  - platform: command_line
    name: HP Ink Level Magenta
    command: /usr/bin/snmpwalk -v1 -c public 192.168.86.21 1.3.6.1.2.1.43.11.1.1 | awk '/.*\.8\.0\.4/ { sub(/.*\./,""); split($0,TT,/[ "]*/); maxlevel=TT[4]; } /.*\.9\.0\.4/ { sub(/.*\./,""); split($0,TT,/[ "]*/); print TT[4] / maxlevel * 100; }'
    unit_of_measurement: '%'
    scan_interval: 14400

group:
  hp_printer:
    name: HP Printer Info
    entities:
      - sensor.hp_ink_level_black
      - sensor.hp_ink_level_yellow
      - sensor.hp_ink_level_cyan
      - sensor.hp_ink_level_magenta

automation:
  - alias: 'Printer Ink Alert'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.hp_ink_level_black
          - sensor.hp_ink_level_yellow
          - sensor.hp_ink_level_cyan
          - sensor.hp_ink_level_magenta
        below: 25
    condition:
      condition: time
      weekday:
        - wed
    action:
    - service: notify.pushbullet_home
      data:
        title: "Home Assistant"
        message: "Low Ink: {{ trigger.to_state.attributes.friendly_name }} is at {{ trigger.to_state.state }}"

